# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10
# terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.


# solution
#fibonacci
# take a number
# add the number that came before it
# (first two numbers are a bit weird)
num_array = []
num = 1
previous_num = 1
# we need to add them up and then
# we need the new_num to become the number
# and the num to become the previous_num
# until n >= 4000000
until num >= 4000000
  new_num = num + previous_num
  #select all even numbers
  if num%2 === 0 then
    num_array << num
  end
  previous_num = num
  num = new_num
end

num_array.reduce(:+)

#add them together
